/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#d4fe42",
        "on-primary": "#4c5f00",
        "primary-container": "#b3db19",
        "on-primary-container": "#3a4900",
        "primary-fixed": "#d1fb3f",
        "primary-dim": "#c6ef33",
        "surface-dim": "#0e0e0e",
        "surface": "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "surface-container": "#1a1919",
        "surface-container-high": "#201f1f",
        "surface-container-highest": "#262626",
        "surface-container-low": "#131313",
        "surface-container-lowest": "#000000",
        "on-surface": "#ffffff",
        "on-surface-variant": "#adaaaa",
        "outline": "#767575",
        "outline-variant": "#484847",
        "secondary": "#e4e2e1",
        "on-secondary": "#525151",
        "background": "#0e0e0e",
        "on-background": "#ffffff",
        error: "#ff7351",
        "error-container": "#b92902",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};